### ISSUE TITLE
[enhancement] Tree shakable

### ISSUE THREAD

**Issue by bartlomiejzuber** [codegateinc/react-smart-scroller#61]
Hello,

I want to use it in one of my projects, although as bundle isn't tree-shekable I would need to pull all of it's components. Is there a chance to convert it to contain modern `esm` modules ?

Here's ref: https://dev.to/iggredible/what-the-heck-are-cjs-amd-umd-and-esm-ikm

Thanks a lot!

**Comment by GrzegorzTarnopolski** [comment]
Hello,

@bartlomiejzuber of course, there is a change to convert it to `esm` modules. I will start working on it but only from Wednesday.

Thank you for reporting.

**Comment by GrzegorzTarnopolski** [comment]
@bartlomiejzuber I have updated this library bundle and build configuration so now it should be tree-shekable

**Comment by bartlomiejzuber** [comment]
Hey, it didn't looks like it is. I am still seeing it as one big file with inline source maps.
As based on latest commits it looks like the build is now targeted to umd, which is fine although it's even less fulfill the requirements I have though.

I'm using your lib with Next.js so your lib should serve cjs (node), umd(old browsers) and esm (modern) module types.

To do it, you can use this tool https://github.com/jaredpalmer/tsdx. It's comparable with microbundle https://github.com/jaredpalmer/tsdx/blob/master/README.md#comparison-to-microbundle. If you need any help with it please let me know as I can prepare PR with it if you don't mind.

**Comment by GrzegorzTarnopolski** [comment]
@bartlomiejzuber feel free to prepare any PR, I am working on it but as I was never creating anything similar, this can take some time to finish

**Comment by GrzegorzTarnopolski** [comment]
@bartlomiejzuber anyway I checked new bundle if it is tree-shakable and the test runs positive.

**Comment by bartlomiejzuber** [comment]
How did you checked it ? What's the test case you've used ? 🤔

**Comment by GrzegorzTarnopolski** [comment]
https://github.com/Rich-Harris/agadoo

**Comment by bartlomiejzuber** [comment]
I pretty sure it's false positive. Yesterday I've checked my production bundle manually and it had all code of this lib regardless that I've used static prop(always the same) to render only `ReactSmartScrollerPagination` version of it while my output had implementations for `ReactSmartScrollerVertical` and `ReactSmartScrollerHorizontal` as well.

Recently you've switched this lib to serve only umd module in a single file. This means that tree shaking doesn't have a chance to work as it's relies on esm modules (quoting the webpacks docs)
https://webpack.js.org/guides/tree-shaking/#add-a-utility
![image](https://user-images.githubusercontent.com/9931428/79425676-57b3b700-7fc2-11ea-8c9b-2cfd308a2a1a.png)

And here's good article about exactly the same problem this lib have:
![image](https://user-images.githubusercontent.com/9931428/79425178-98f79700-7fc1-11ea-93eb-edd14f5218d6.png)
https://dev.to/lukasbombach/how-to-write-a-tree-shakable-component-library-4ied

I would recommend use a external service to easily check if your bundle supports tree shaking https://bundlephobia.com/result?p=react-smart-scroller@1.0.22 or if you really don't trust it just use you're bundle as expected and check the output code.

**Comment by GrzegorzTarnopolski** [comment]
ok, now I see what is the main point. I converted bundle to tree-shaking, but you will see those  `ReactSmartScrollerPagination`, `ReactSmartScrollerVertical ` and `ReactSmartScrollerHorizontal ` because of `ReactSmartScroller`, it was designed to export one single component that does everything. If you would like to make it really tree-shakable I would need to restructure `react-smart-scroller` so it exports 3 components rather than 1, then it will be tree-shakable.

**Comment by bartlomiejzuber** [comment]
Nah mate, that's something tree shaking is meant to be doing. You only need to turn it on properly and webpack's tree shaking will do the rest.
