### ISSUE TITLE
Could not find dependency: 'lib' relative to '/node_modules/react-smart-scroller/dist/react-smart-scroller.cjs.development.js'

### ISSUE THREAD

**Issue by ialpert** [codegateinc/react-smart-scroller#68]
**Describe the bug**
Version 1.1.0 has reference to "lib" that is part of the source code but does not belong to the production package

**To Reproduce**
1. https://codesandbox.io/s/musing-mahavira-vytix?file=/package.json

**Comment by GrzegorzTarnopolski** [comment]
Hi,
thank you for reporting the issue. It is my fault that I haven't tried this before the new npm push.

I fixed the problem -> [https://codesandbox.io/s/objective-archimedes-8bjzd](url)

If something will be not as expected please feel free to open issue

**Comment by ialpert** [comment]
Thank you for such a quick turn-around @GrzegorzTarnopolski !
