### ISSUE TITLE
Remove assets from the package

### ISSUE THREAD

**Issue by ialpert** [codegateinc/react-smart-scroller#70]
**Is your feature request related to a problem? Please describe.**

Optimization request

**Describe the solution you'd like**
Currently, the folder with assets (animated Gifs for demo) is included in the package, but I assume it has no use for the library itself. It is nice 25Mb (other dist files are 600Kb)

Maybe it is possible to ignore it from the npm package so it takes less space and installs faster?

Thanks!

**Comment by GrzegorzTarnopolski** [comment]
Hello @ialpert,

I will take care of it, sorry for the long response

**Comment by ialpert** [comment]
Dziękuję!

**Comment by GrzegorzTarnopolski** [comment]
@ialpert 

It is done, I am closing this PR
