### ISSUE TITLE
Contributor request with new feature

### ISSUE THREAD

**Issue by silverfh** [codegateinc/react-smart-scroller#73]
Hi,

let me say first... I been to many scroller components since last few days and this is so far the best I found...

I have just created an added feature to your plugin... adding navigation arrows on demand..
and I would like to share my addition to this hub.. can you add me as a collaborator or if you would like me so share my code updates any other way ? just want to share my addition ... 

Thanks
Faheem

**Comment by GrzegorzTarnopolski** [comment]
Hi @silverfh,

thank you for your message. There is already a feature for custom arrows, `renderPagination`, also there is an example of how to implement it.

Thanks,
Greg
