### ISSUE TITLE
startAt startIndex not setting position

### ISSUE THREAD

**Issue by bcole2433** [codegateinc/react-smart-scroller#76]
Working with the new startAt feature recently released. It does not seem to be updating position based on what the startIndex is set at. The scroll direction is horizontal.
Reactjs, javascript
react-smart-scroller 1.1.4

Below is the code I am using:

`<div className={eventClasses.tickerContainer}>
          <ReactSmartScroller
              numCols={colNumber}
              pagination
              draggable
              startAt={{
                startIndex: 2
              }}
paginationConfig={{
                draggable: true,
                activeDotColor: "#000",
                unactiveDotsColor: "#ededed",
              }}
          >
{boxscores.map((boxscore) => (
              <EventBox key={boxscore?.officialId} eventData={boxscore} />
            ))}
          </ReactSmartScroller>
        </div>`

**Comment by GrzegorzTarnopolski** [comment]
Hi,

new version 1.1.5 has been pushed with pagination that handles `startAt` prop,
Please check it out if this works.

**Comment by GrzegorzTarnopolski** [comment]
@bcole2433 did you test it?

**Comment by GrzegorzTarnopolski** [comment]
if any issue will occur with this topic please reopen
