### ISSUE TITLE
Children width with pagination true

### ISSUE THREAD

**Issue by onmironov** [codegateinc/react-smart-scroller#81]
If I use `pagination === true`, children width is 100%, but I need child width. And scroll does't work, only click by arrows.
If I use `pagination === false` — all is ok, but I need arrow and `onNext`.

**Comment by GrzegorzTarnopolski** [comment]
Hi @onmironov 
please tell me more details about what you are trying to achieve, for now, I understood that you want to have a scroller and also an arrow to navigate through children right?

**Comment by onmironov** [comment]
Yes, I have two problems, when `pagination === true`:
1. I need a scroll
2. I need children of their own width, not 100%

**Comment by GrzegorzTarnopolski** [comment]
@onmironov 
of course, it is possible, I will implement it when I will have some time, now I'm a little busy

**Comment by GrzegorzTarnopolski** [comment]
@onmironov please try now by pulling a new version, simply set pagination to false and pass paginationConfig: `withScroll` now you will have scroll and pagination, also you can render your own pagination with it as well

**Comment by onmironov** [comment]
But now I have a scrollbar

**Comment by GrzegorzTarnopolski** [comment]
If you don't want to have scrollbar just pass pagination prop with paginationConfig with `withScroll`

**Comment by GrzegorzTarnopolski** [comment]
@onmironov please try above

**Comment by onmironov** [comment]
@GrzegorzTarnopolski no, it does't work. If I use `withScroll: true` I have a scrollbar. If `withScroll: false`, I don't have `onPrev` and `onNext`

**Comment by GrzegorzTarnopolski** [comment]
@onmironov https://codesandbox.io/s/eager-goldstine-w0gvq?file=/src/App.tsx

**Comment by onmironov** [comment]
@GrzegorzTarnopolski and we a have a first problem https://codesandbox.io/s/bitter-frost-wkc5j?file=/src/App.tsx

**Comment by GrzegorzTarnopolski** [comment]
@onmironov please describe the problem because I don't see any problem

**Comment by onmironov** [comment]
@GrzegorzTarnopolski here https://codesandbox.io/s/bitter-frost-wkc5j?file=/src/App.tsx I have scrollbar, this is a problem of this issue

**Comment by GrzegorzTarnopolski** [comment]
@onmironov https://codesandbox.io/s/thirsty-buck-30ks4?file=/src/App.tsx

**Comment by onmironov** [comment]
@GrzegorzTarnopolski https://codesandbox.io/s/long-sound-wwby7?file=/src/App.tsx
`children width is 100%, but I need child width`

**Comment by GrzegorzTarnopolski** [comment]
@onmironov so you want them to be close one to another? and have width as in above example?

**Comment by onmironov** [comment]
@GrzegorzTarnopolski yes, I want child width like `pagination === false`

**Comment by GrzegorzTarnopolski** [comment]
@onmironov https://codesandbox.io/s/awesome-cloud-jpq2o?file=/src/App.tsx

**Comment by onmironov** [comment]
@GrzegorzTarnopolski nothing changed

**Comment by GrzegorzTarnopolski** [comment]
@onmironov update to 1.1.20
